import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ChevronLeft, ChevronRight, Plus, Search, Trash2 } from 'lucide-react';
import { useNavigate, useParams } from 'react-router';
import { toast } from 'sonner';
import { godownService, inventoryService } from '../../services/inventoryService';

export const InventoryMovement = () => {
  const navigate=useNavigate(); const { type }=useParams(); const movementType=type==='out'?'out':'in';
  const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [transport,setTransport]=useState('freight_vehicle'); const [slip,setSlip]=useState<File|null>(null);
  const [items,setItems]=useState<any[]>([]); const [godowns,setGodowns]=useState<any[]>([]); const [products,setProducts]=useState<any[]>([]); const [productPage,setProductPage]=useState(1); const [productMeta,setProductMeta]=useState<any>({total:0,last_page:1}); const [productsLoading,setProductsLoading]=useState(false); const [open,setOpen]=useState(false); const [search,setSearch]=useState(''); const [saving,setSaving]=useState(false);
  const productRequestId=useRef(0);
  useEffect(()=>{void godownService.list(true).then(setGodowns);},[]);
  const loadProducts=async(page:number)=>{const requestId=++productRequestId.current;setProductsLoading(true);try{const result=await inventoryService.selectableProducts({search,movement_type:movementType,page});if(requestId!==productRequestId.current)return;setProducts(result.data||[]);setProductMeta(result.meta?.pagination||{});setProductPage(page);}finally{if(requestId===productRequestId.current)setProductsLoading(false);}};
  useEffect(()=>{if(!open)return;const timer=setTimeout(()=>void loadProducts(1),300);return()=>clearTimeout(timer);},[open,search,movementType]);
  const totalPackages=useMemo(()=>items.reduce((sum,item)=>sum+Number(item.packages||0),0),[items]);
  const addProduct=(product:any)=>{const availableGodowns=movementType==='out'?godowns.filter(g=>Number(product.quantities?.find((q:any)=>String(q.godown_id)===String(g.id))?.quantity||0)>0):godowns;setItems(current=>[...current,{product_id:product.id,product_name:product.product_name||product.name,model_number:product.model_number||product.modelNumber,brand:product.brand?.name||product.brand||'',measurement_unit:product.measurement_unit||'',stock_quantities:product.quantities||[],godown_id:availableGodowns[0]?.id||'',quantity:'',packages:''}]);setOpen(false);setSearch('');};
  const update=(index:number,key:string,value:any)=>setItems(current=>current.map((item,i)=>i===index?{...item,[key]:value}:item));
  const stockInGodown=(item:any,godownId:any)=>Number(item.stock_quantities?.find((stock:any)=>String(stock.godown_id)===String(godownId))?.quantity||0);
  const godownsForItem=(item:any)=>movementType==='out'?godowns.filter(godown=>stockInGodown(item,godown.id)>0):godowns;
  const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!items.length){toast.error('Add at least one product');return;}setSaving(true);try{const fd=new FormData();fd.append('movement_date',date);fd.append('movement_type',movementType);fd.append('transport_type',transport);if(slip)fd.append('slip',slip);items.forEach((item,i)=>{fd.append(`items[${i}][product_id]`,String(item.product_id));fd.append(`items[${i}][godown_id]`,String(item.godown_id));fd.append(`items[${i}][quantity]`,String(item.quantity));fd.append(`items[${i}][packages]`,String(item.packages));});await inventoryService.createMovement(fd);toast.success(`${movementType.toUpperCase()} inventory saved`);navigate('/inventory');}catch(error:any){toast.error(Object.values(error?.errors||{})?.flat()?.[0] as string||'Unable to save movement');}finally{setSaving(false);}};
  return <div className="p-4 sm:p-6 lg:p-8"><form onSubmit={submit} className="mx-auto max-w-6xl space-y-6"><div className="flex items-center gap-3"><button type="button" onClick={()=>navigate('/inventory')} className="p-2"><ArrowLeft/></button><div><h2 className="text-2xl font-semibold">{movementType==='in'?'IN':'OUT'} Item Inventory Movement</h2><p className="text-sm text-gray-500">Record stock {movementType==='in'?'received':'issued'}</p></div></div>
    <div className="grid gap-5 rounded-2xl border bg-white p-6 md:grid-cols-3"><div><label className="mb-2 block text-sm font-medium">Date *</label><input required type="date" value={date} onChange={e=>setDate(e.target.value)} className="w-full rounded-xl border px-4 py-3"/></div><div><label className="mb-2 block text-sm font-medium">Transport Type *</label><select value={transport} onChange={e=>setTransport(e.target.value)} className="w-full rounded-xl border px-4 py-3"><option value="freight_vehicle">Freight Vehicle</option><option value="courier">Courier</option></select></div><div><label className="mb-2 block text-sm font-medium">Vehicle/Courier Slip</label><input type="file" accept="image/*,.pdf" onChange={e=>setSlip(e.target.files?.[0]||null)} className="w-full rounded-xl border px-3 py-2.5"/></div></div>
    <div className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between border-b p-5"><div><h3 className="font-semibold">Products</h3><p className="text-sm text-gray-500">Final package quantity: <b>{totalPackages}</b></p></div><button type="button" onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-white"><Plus className="h-4 w-4"/>Add Product</button></div><div className="overflow-x-auto"><table className="w-full min-w-[800px]"><thead className="bg-gray-50"><tr><th className="px-4 py-3 text-left">Product</th><th className="px-4 py-3 text-left">Godown</th><th className="px-4 py-3 text-left">Qty</th><th className="px-4 py-3 text-left">Pkgs per Qty</th><th></th></tr></thead><tbody className="divide-y">{items.map((item,i)=><tr key={`${item.product_id}-${i}`}><td className="px-4 py-3"><div className="font-medium">{item.product_name}</div><div className="text-xs text-gray-500">{item.model_number} {item.brand&&`• ${item.brand}`} {item.measurement_unit&&`• ${item.measurement_unit}`}</div></td><td className="px-4 py-3"><select required value={item.godown_id} onChange={e=>update(i,'godown_id',e.target.value)} className="w-full rounded-lg border px-3 py-2"><option value="">Select</option>{godownsForItem(item).map(g=><option key={g.id} value={g.id}>{g.name}{movementType==='out'?` (Available: ${stockInGodown(item,g.id)})`:''}</option>)}</select></td><td className="px-4 py-3"><input required min="0.001" max={movementType==='out'?stockInGodown(item,item.godown_id):undefined} step="0.001" type="number" value={item.quantity} onChange={e=>update(i,'quantity',e.target.value)} className="w-32 rounded-lg border px-3 py-2"/><div className="mt-1 text-xs text-gray-500">{item.measurement_unit||'Unit'}{movementType==='out'?` • Available ${stockInGodown(item,item.godown_id)}`:''}</div></td><td className="px-4 py-3"><input required min="1" step="1" type="number" value={item.packages} onChange={e=>update(i,'packages',e.target.value)} className="w-28 rounded-lg border px-3 py-2"/></td><td><button type="button" onClick={()=>setItems(v=>v.filter((_,x)=>x!==i))} className="p-2 text-red-600"><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table>{!items.length&&<div className="p-10 text-center text-gray-500">Click Add Product to begin.</div>}</div></div>
    <div className="flex justify-end gap-3"><button type="button" onClick={()=>navigate('/inventory')} className="rounded-xl border px-6 py-3">Cancel</button><button disabled={saving} className="rounded-xl bg-blue-600 px-6 py-3 text-white disabled:opacity-60">{saving?'Saving...':`Save ${movementType.toUpperCase()} Movement`}</button></div>
    {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[80vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6"><div className="mb-5 flex justify-between"><h3 className="text-xl font-semibold">Select Product</h3><button type="button" onClick={()=>setOpen(false)}>✕</button></div><div className="relative mb-4"><Search className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400"/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search product, model or brand" className="w-full rounded-xl border py-3 pl-10 pr-4"/></div>{productsLoading&&<div className="py-8 text-center text-sm text-gray-500">Searching products...</div>}<div className="grid gap-3 md:grid-cols-2">{!productsLoading&&products.map(product=><button type="button" key={product.id} onClick={()=>addProduct(product)} className="rounded-xl border p-4 text-left hover:border-blue-500 hover:bg-blue-50"><div className="font-medium">{product.product_name||product.name}</div><div className="text-sm text-gray-500">{product.model_number||product.modelNumber||'-'} • {product.brand?.name||product.brand||'No brand'} • {product.measurement_unit||'Unit'}</div><div className="mt-2 text-sm font-semibold text-gray-800">Total Qty: {Number(product.total_quantity||0).toLocaleString('en-IN')}</div><div className="mt-1 flex flex-wrap gap-1">{product.quantities?.filter((stock:any)=>movementType==='in'||Number(stock.quantity)>0).map((stock:any)=><span key={stock.godown_id} className="rounded bg-gray-100 px-2 py-1 text-xs text-gray-600">{stock.godown}: {stock.quantity}</span>)}</div></button>)}</div>{!productsLoading&&!products.length&&<div className="py-10 text-center text-gray-500">{movementType==='out'?'No products with available stock found.':'No products found.'}</div>}<div className="mt-5 flex items-center justify-between border-t pt-4"><span className="text-sm text-gray-500">{productMeta.total||0} products • 50 per page</span><div className="flex items-center gap-2"><button type="button" disabled={productPage<=1||productsLoading} onClick={()=>void loadProducts(productPage-1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4"/></button><span className="text-sm">{productPage} / {productMeta.last_page||1}</span><button type="button" disabled={productPage>=(productMeta.last_page||1)||productsLoading} onClick={()=>void loadProducts(productPage+1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronRight className="h-4 w-4"/></button></div></div></div></div>}
  </form></div>;
};
